# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'cadastroUsuario.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.senha = QtWidgets.QLabel(self.centralwidget)
        self.senha.setObjectName("senha")
        self.gridLayout.addWidget(self.senha, 1, 0, 1, 1)
        self.usuario = QtWidgets.QLabel(self.centralwidget)
        self.usuario.setObjectName("usuario")
        self.gridLayout.addWidget(self.usuario, 0, 0, 1, 1)
        self.senhaEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.senhaEdit.setObjectName("senhaEdit")
        self.gridLayout.addWidget(self.senhaEdit, 1, 1, 1, 1)
        self.usuarioEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.usuarioEdit.setObjectName("usuarioEdit")
        self.gridLayout.addWidget(self.usuarioEdit, 0, 1, 1, 1)
        self.enviarCadastro = QtWidgets.QPushButton(self.centralwidget)
        self.enviarCadastro.setObjectName("enviarCadastro")
        self.gridLayout.addWidget(self.enviarCadastro, 2, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 227, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.senha.setText(_translate("MainWindow", "Senha"))
        self.usuario.setText(_translate("MainWindow", "Usuario"))
        self.enviarCadastro.setText(_translate("MainWindow", "Cadastrar"))
